### ISSUE TITLE
Please Help Rtl8812BU supports monitor mode? Packet Injection? evil-Twin Attack?

### ISSUE THREAD

**Issue by saineox** [kolki1973/rtl88x2bu#1]
Please Help
 Rtl8812BU supports 
monitor mode? 
Packet Injection?
 evil-Twin Attack?
Kali linux supported or not

need to buy new

**Comment by kolki1973** [comment]
This driver for the RTL8812BU/RTL8822 chipsets supports STA/Monitor Mode, but no AP, so "EvilTwin-Attack" isn't possible. It should run fine on Kali Linux, but I have not tested it; I'm just using Gentoo. 
https://www.aircrack-ng.org/doku.php?id=compatibility_drivers
